"""actualizar modelos empresa y eventos

Revision ID: 1f995421de6e
Revises: f54fe3d57be0
Create Date: 2026-06-14 11:03:34.483232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f995421de6e'
down_revision = 'f54fe3d57be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_legal', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('cif_nif', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['cif_nif'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cif_nif')
        batch_op.drop_column('nombre_legal')

    # ### end Alembic commands ###
