"""empty message

Revision ID: 4e43d7475262
Revises: 62e511026b76
Create Date: 2026-07-09 08:52:30.508408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e43d7475262'
down_revision = '62e511026b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_session_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy', schema=None) as batch_op:
        batch_op.drop_column('stripe_session_id')

    # ### end Alembic commands ###
