"""empty message

Revision ID: 62e511026b76
Revises: 
Create Date: 2026-07-05 16:50:43.314725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e511026b76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_code', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['ticket_code'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('username_changed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=500), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('avatar')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('username_changed')
        batch_op.drop_column('username')

    with op.batch_alter_table('buy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ticket_code')

    # ### end Alembic commands ###
