"""empty message

Revision ID: a89ed922689b
Revises: 
Create Date: 2026-06-19 17:42:52.518737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89ed922689b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_event_follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_legal', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('cif_nif', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['cif_nif'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cif_nif')
        batch_op.drop_column('nombre_legal')

    op.drop_table('user_event_follow')
    # ### end Alembic commands ###
